-- ============================================================
-- 20260919_snake_to_pascal_rename.sql
-- YZH 铁律落地：DB 列名 = C# 属性名 = PascalCase
-- 由实体（CertPlatform.Shared/Entities + yzh-core）反推生成，幂等：
--   仅当「旧列存在且新列不存在」时才 RENAME，可重复执行。
-- MySQL 8.0：使用 ALTER TABLE ... RENAME COLUMN（保留类型/默认值/注释）
-- ============================================================


-- ── cert_ai_config ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'api_key');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'ApiKey');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_ai_config` RENAME COLUMN `api_key` TO `ApiKey`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'is_enabled');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'IsEnabled');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_ai_config` RENAME COLUMN `is_enabled` TO `IsEnabled`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'max_tokens');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_ai_config' AND COLUMN_NAME = 'MaxTokens');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_ai_config` RENAME COLUMN `max_tokens` TO `MaxTokens`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_doc_extraction_rule ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'doc_content');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'DocContent');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `doc_content` TO `DocContent`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'file_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'FileCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `file_code` TO `FileCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'phase_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'PhaseCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `phase_code` TO `PhaseCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'sample_data');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'SampleData');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `sample_data` TO `SampleData`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'standard_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'StandardCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `standard_code` TO `StandardCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'standard_file_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'StandardFileCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `standard_file_code` TO `StandardFileCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'verify_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_extraction_rule' AND COLUMN_NAME = 'VerifyMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_extraction_rule` RENAME COLUMN `verify_message` TO `VerifyMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_doc_field_def ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'data_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'DataType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `data_type` TO `DataType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'field_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'FieldCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `field_code` TO `FieldCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'field_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'FieldName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `field_name` TO `FieldName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'is_ai_recommended');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'IsAiRecommended');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `is_ai_recommended` TO `IsAiRecommended`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'is_manual');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'IsManual');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `is_manual` TO `IsManual`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'rule_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_field_def' AND COLUMN_NAME = 'RuleCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_field_def` RENAME COLUMN `rule_code` TO `RuleCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_doc_table_def ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'rule_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'RuleCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_def` RENAME COLUMN `rule_code` TO `RuleCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'table_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'TableCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_def` RENAME COLUMN `table_code` TO `TableCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'table_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_def' AND COLUMN_NAME = 'TableName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_def` RENAME COLUMN `table_name` TO `TableName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_doc_table_field_def ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'column_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'ColumnCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_field_def` RENAME COLUMN `column_code` TO `ColumnCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'column_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'ColumnName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_field_def` RENAME COLUMN `column_name` TO `ColumnName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'data_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'DataType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_field_def` RENAME COLUMN `data_type` TO `DataType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'table_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_doc_table_field_def' AND COLUMN_NAME = 'TableCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_doc_table_field_def` RENAME COLUMN `table_code` TO `TableCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_message ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'extra_data');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'ExtraData');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `extra_data` TO `ExtraData`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'is_read');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'IsRead');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `is_read` TO `IsRead`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'message_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'MessageType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `message_type` TO `MessageType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'read_date');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'ReadDate');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `read_date` TO `ReadDate`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'user_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'UserCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `user_code` TO `UserCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'user_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_message' AND COLUMN_NAME = 'UserName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_message` RENAME COLUMN `user_name` TO `UserName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_org_stage ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_stage' AND COLUMN_NAME = 'phase_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_stage' AND COLUMN_NAME = 'StageCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_org_stage` RENAME COLUMN `phase_code` TO `StageCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_stage' AND COLUMN_NAME = 'standard_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_stage' AND COLUMN_NAME = 'StandardCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_org_stage` RENAME COLUMN `standard_code` TO `StandardCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_org_standard ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_standard' AND COLUMN_NAME = 'standard_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_org_standard' AND COLUMN_NAME = 'StandardCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_org_standard` RENAME COLUMN `standard_code` TO `StandardCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_standard_directory_config ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_config' AND COLUMN_NAME = 'Enable_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_config' AND COLUMN_NAME = 'EnableField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_config` RENAME COLUMN `Enable_field` TO `EnableField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_config' AND COLUMN_NAME = 'Status_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_config' AND COLUMN_NAME = 'StatusField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_config` RENAME COLUMN `Status_field` TO `StatusField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_standard_directory_file ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'Enable_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'EnableField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `Enable_field` TO `EnableField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'Status_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'StatusField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `Status_field` TO `StatusField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'convert_date');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'ConvertDate');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `convert_date` TO `ConvertDate`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'convert_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'ConvertMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `convert_message` TO `ConvertMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'convert_status');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'ConvertStatus');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `convert_status` TO `ConvertStatus`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'converted_storage_path');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'ConvertedStoragePath');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `converted_storage_path` TO `ConvertedStoragePath`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'file_size');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'FileSize');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `file_size` TO `FileSize`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'markdown_date');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'MarkdownDate');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `markdown_date` TO `MarkdownDate`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'markdown_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'MarkdownMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `markdown_message` TO `MarkdownMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'markdown_path');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'MarkdownPath');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `markdown_path` TO `MarkdownPath`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'markdown_status');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'MarkdownStatus');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `markdown_status` TO `MarkdownStatus`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'preview_pdf_path');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_file' AND COLUMN_NAME = 'PreviewPdfPath');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_file` RENAME COLUMN `preview_pdf_path` TO `PreviewPdfPath`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── cert_standard_directory_folder ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_folder' AND COLUMN_NAME = 'Enable_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_folder' AND COLUMN_NAME = 'EnableField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_folder` RENAME COLUMN `Enable_field` TO `EnableField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_folder' AND COLUMN_NAME = 'Status_field');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'cert_standard_directory_folder' AND COLUMN_NAME = 'StatusField');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `cert_standard_directory_folder` RENAME COLUMN `Status_field` TO `StatusField`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_execution_task ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'cache_keys');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'CacheKeys');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `cache_keys` TO `CacheKeys`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'completed_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'CompletedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `completed_at` TO `CompletedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'config_snapshot');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'ConfigSnapshot');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `config_snapshot` TO `ConfigSnapshot`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'duration_ms');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'DurationMs');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `duration_ms` TO `DurationMs`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'enterprise_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'EnterpriseCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `enterprise_code` TO `EnterpriseCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'error_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'ErrorMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `error_message` TO `ErrorMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'phase_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'PhaseCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `phase_code` TO `PhaseCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'queue_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'QueueCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `queue_code` TO `QueueCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'result_summary');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'ResultSummary');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `result_summary` TO `ResultSummary`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'rule_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'RuleCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `rule_code` TO `RuleCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'started_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'StartedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `started_at` TO `StartedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'task_status');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'TaskStatus');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `task_status` TO `TaskStatus`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'task_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task' AND COLUMN_NAME = 'TaskType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task` RENAME COLUMN `task_type` TO `TaskType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_execution_task_item ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'cache_keys');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'CacheKeys');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `cache_keys` TO `CacheKeys`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'completed_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'CompletedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `completed_at` TO `CompletedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'duration_ms');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'DurationMs');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `duration_ms` TO `DurationMs`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'error_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'ErrorMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `error_message` TO `ErrorMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'is_success');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'IsSuccess');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `is_success` TO `IsSuccess`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'item_status');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'ItemStatus');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `item_status` TO `ItemStatus`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'item_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'ItemType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `item_type` TO `ItemType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'result_summary');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'ResultSummary');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `result_summary` TO `ResultSummary`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'rule_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'RuleCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `rule_code` TO `RuleCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'started_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'StartedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `started_at` TO `StartedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'task_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_execution_task_item' AND COLUMN_NAME = 'TaskCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_execution_task_item` RENAME COLUMN `task_code` TO `TaskCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_node_execution ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'completed_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'CompletedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `completed_at` TO `CompletedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'error_message');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'ErrorMessage');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `error_message` TO `ErrorMessage`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'exec_status');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'ExecStatus');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `exec_status` TO `ExecStatus`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'execution_time_ms');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'ExecutionTimeMs');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `execution_time_ms` TO `ExecutionTimeMs`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'is_reused');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'IsReused');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `is_reused` TO `IsReused`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'item_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'ItemCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `item_code` TO `ItemCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'node_id');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'NodeId');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `node_id` TO `NodeId`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'node_title');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'NodeTitle');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `node_title` TO `NodeTitle`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'node_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'NodeType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `node_type` TO `NodeType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'output_json');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'OutputJson');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `output_json` TO `OutputJson`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'skill_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'SkillCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `skill_code` TO `SkillCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'started_at');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'StartedAt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `started_at` TO `StartedAt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'task_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_node_execution' AND COLUMN_NAME = 'TaskCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_node_execution` RENAME COLUMN `task_code` TO `TaskCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_prompt_template ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'is_active');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'IsActive');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `is_active` TO `IsActive`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'last_test_result');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'LastTestResult');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `last_test_result` TO `LastTestResult`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'org_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'OrgCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `org_code` TO `OrgCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'prompt_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'PromptCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `prompt_code` TO `PromptCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'prompt_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'PromptName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `prompt_name` TO `PromptName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'prompt_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'PromptType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `prompt_type` TO `PromptType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'skill_target');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_prompt_template' AND COLUMN_NAME = 'SkillTarget');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_prompt_template` RENAME COLUMN `skill_target` TO `SkillTarget`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_skill ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'category_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'CategoryCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `category_code` TO `CategoryCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'is_active');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'IsActive');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `is_active` TO `IsActive`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'output_strict');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'OutputStrict');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `output_strict` TO `OutputStrict`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'prompt_template');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'PromptTemplate');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `prompt_template` TO `PromptTemplate`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'return_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'ReturnType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `return_type` TO `ReturnType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'side_effect');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'SideEffect');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `side_effect` TO `SideEffect`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'skill_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'SkillCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `skill_code` TO `SkillCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'skill_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'SkillType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `skill_type` TO `SkillType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'sort_order');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill' AND COLUMN_NAME = 'SortOrder');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill` RENAME COLUMN `sort_order` TO `SortOrder`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_skill_category ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'category_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'CategoryCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_category` RENAME COLUMN `category_code` TO `CategoryCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'category_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'Name');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_category` RENAME COLUMN `category_name` TO `Name`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'sort_order');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_category' AND COLUMN_NAME = 'SortOrder');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_category` RENAME COLUMN `sort_order` TO `SortOrder`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_skill_input ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'bind_mode');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'BindMode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `bind_mode` TO `BindMode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'default_value');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'DefaultValue');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `default_value` TO `DefaultValue`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'enum_source');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'EnumSource');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `enum_source` TO `EnumSource`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'input_label');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'InputLabel');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `input_label` TO `InputLabel`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'input_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'InputName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `input_name` TO `InputName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'input_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'InputType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `input_type` TO `InputType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'is_required');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'IsRequired');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `is_required` TO `IsRequired`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'skill_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'SkillCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `skill_code` TO `SkillCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'sort_order');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_input' AND COLUMN_NAME = 'SortOrder');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_input` RENAME COLUMN `sort_order` TO `SortOrder`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_skill_output ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'output_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'OutputName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_output` RENAME COLUMN `output_name` TO `OutputName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'output_prompt');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'OutputPrompt');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_output` RENAME COLUMN `output_prompt` TO `OutputPrompt`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'output_type');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'OutputType');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_output` RENAME COLUMN `output_type` TO `OutputType`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'skill_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'SkillCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_output` RENAME COLUMN `skill_code` TO `SkillCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'sort_order');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_output' AND COLUMN_NAME = 'SortOrder');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_output` RENAME COLUMN `sort_order` TO `SortOrder`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- ── wf_skill_reflection ──
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'class_path');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'ClassPath');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_reflection` RENAME COLUMN `class_path` TO `ClassPath`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'method_name');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'MethodName');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_reflection` RENAME COLUMN `method_name` TO `MethodName`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'param_binding');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'ParamBinding');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_reflection` RENAME COLUMN `param_binding` TO `ParamBinding`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @has := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'skill_code');
SET @new := (SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'wf_skill_reflection' AND COLUMN_NAME = 'SkillCode');
SET @sql := IF(@has = 1 AND @new = 0, 'ALTER TABLE `wf_skill_reflection` RENAME COLUMN `skill_code` TO `SkillCode`', 'DO 0');
PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
