-- ============================================================
-- yzh_queue + yzh_queue_task + yzh_queue_resource_lock DDL
-- 数据库：yzh_cert_platform
-- 字符集：utf8mb4（与现有表一致）
-- ============================================================

-- 1. 队列主表
CREATE TABLE IF NOT EXISTS yzh_queue (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(36) NOT NULL COMMENT '全局唯一编码(GUID)',
  queue_code VARCHAR(64) NOT NULL COMMENT '队列业务编码：Q-{yyyyMMdd}-{6位随机}',
  queue_type VARCHAR(30) NOT NULL COMMENT '队列类型：file_convert/auto_verify/report_generate',
  queue_name VARCHAR(200) DEFAULT NULL COMMENT '队列名称（人话）',
  scope_key VARCHAR(200) DEFAULT NULL COMMENT '范围键（按类型约定格式）',
  scope_info TEXT DEFAULT NULL COMMENT '冗余展示数据 JSON',
  source_type VARCHAR(30) DEFAULT NULL COMMENT '来源类型：upload_task/verify_req/report_req',
  source_id VARCHAR(64) DEFAULT NULL COMMENT '来源ID',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/running/completed/failed/cancelled',
  total_count INT NOT NULL DEFAULT 0,
  pending_count INT NOT NULL DEFAULT 0,
  processing_count INT NOT NULL DEFAULT 0,
  completed_count INT NOT NULL DEFAULT 0,
  failed_count INT NOT NULL DEFAULT 0,
  cancelled_count INT NOT NULL DEFAULT 0,
  progress INT NOT NULL DEFAULT 0,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  remark VARCHAR(500) DEFAULT NULL,
  org_code VARCHAR(50) DEFAULT NULL,
  create_id INT DEFAULT NULL,
  creator VARCHAR(50) DEFAULT NULL,
  create_date DATETIME DEFAULT NULL,
  modify_id INT DEFAULT NULL,
  modifier VARCHAR(50) DEFAULT NULL,
  modify_date DATETIME DEFAULT NULL,
  delete_id INT DEFAULT NULL,
  deleter VARCHAR(50) DEFAULT NULL,
  delete_time DATETIME DEFAULT NULL,
  UNIQUE KEY uk_queue_code (queue_code),
  KEY idx_queue_status (status),
  KEY idx_queue_type (queue_type),
  KEY idx_queue_scope (scope_key),
  KEY idx_queue_source (source_type, source_id),
  KEY idx_queue_create_date (create_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='yzh 队列主表';

-- 2. 队列子任务表
CREATE TABLE IF NOT EXISTS yzh_queue_task (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(36) NOT NULL COMMENT '全局唯一编码(GUID)',
  queue_code VARCHAR(64) NOT NULL COMMENT '所属队列编码(yzh_queue.queue_code)',
  task_type VARCHAR(30) NOT NULL COMMENT '任务类型：file_convert/auto_verify/report_generate',
  payload TEXT DEFAULT NULL COMMENT '业务数据 JSON',
  status VARCHAR(20) NOT NULL DEFAULT 'pending' COMMENT '状态：pending/processing/completed/failed/cancelled',
  error_type VARCHAR(20) DEFAULT NULL COMMENT '错误分类：retryable/permanent',
  error_message VARCHAR(2000) DEFAULT NULL COMMENT '错误信息',
  retry_count INT NOT NULL DEFAULT 0,
  max_retry_count INT NOT NULL DEFAULT 3,
  next_retry_at DATETIME DEFAULT NULL COMMENT '下次重试时间（指数退避）',
  locked_until DATETIME DEFAULT NULL COMMENT '领取租约到期时间',
  locked_at DATETIME DEFAULT NULL COMMENT '领取时间',
  locked_by VARCHAR(100) DEFAULT NULL COMMENT '领取 Worker 标识',
  process_time DATETIME DEFAULT NULL COMMENT '开始处理时间',
  complete_time DATETIME DEFAULT NULL COMMENT '完成/失败/取消时间',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '入队时间',
  task_id VARCHAR(64) DEFAULT NULL COMMENT '来源批次ID',
  user_id INT DEFAULT NULL COMMENT '发起用户ID',
  user_name VARCHAR(100) DEFAULT NULL COMMENT '发起用户名',
  org_code VARCHAR(50) DEFAULT NULL COMMENT '机构编码',
  priority INT NOT NULL DEFAULT 0 COMMENT '优先级（0=普通，10=高优先）',
  lock_codes VARCHAR(500) DEFAULT NULL COMMENT '本任务持有的资源锁编码（逗号分隔）',
  create_id INT DEFAULT NULL,
  creator VARCHAR(50) DEFAULT NULL,
  create_date DATETIME DEFAULT NULL,
  modify_id INT DEFAULT NULL,
  modifier VARCHAR(50) DEFAULT NULL,
  modify_date DATETIME DEFAULT NULL,
  delete_id INT DEFAULT NULL,
  deleter VARCHAR(50) DEFAULT NULL,
  delete_time DATETIME DEFAULT NULL,
  UNIQUE KEY uk_task_code (code),
  KEY idx_task_queue_code (queue_code),
  KEY idx_task_status (status),
  KEY idx_task_type (task_type),
  KEY idx_task_pending (status, priority DESC, create_time),
  KEY idx_task_task_id (task_id),
  KEY idx_task_locked (status, locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='yzh 队列子任务表';

-- 3. 队列资源锁定表
CREATE TABLE IF NOT EXISTS yzh_queue_resource_lock (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  code VARCHAR(36) NOT NULL COMMENT '全局唯一编码(GUID)',
  queue_code VARCHAR(64) NOT NULL COMMENT '所属队列编码',
  resource_table VARCHAR(50) NOT NULL COMMENT '资源表名',
  resource_code VARCHAR(200) NOT NULL COMMENT '资源唯一编码',
  resource_name VARCHAR(200) DEFAULT NULL COMMENT '资源名称快照',
  task_no INT DEFAULT NULL COMMENT '占用该资源的子任务序号（NULL=队列级锁）',
  status VARCHAR(20) NOT NULL DEFAULT 'locked' COMMENT '状态：locked/released',
  active_key VARCHAR(260) DEFAULT NULL COMMENT '活跃锁键（resource_table|resource_code）',
  create_time DATETIME DEFAULT NULL COMMENT '加锁时间',
  release_time DATETIME DEFAULT NULL COMMENT '释放时间',
  expire_at DATETIME DEFAULT NULL COMMENT '锁租约安全网',
  org_code VARCHAR(50) DEFAULT NULL,
  create_id INT DEFAULT NULL,
  creator VARCHAR(50) DEFAULT NULL,
  create_date DATETIME DEFAULT NULL,
  modify_id INT DEFAULT NULL,
  modifier VARCHAR(50) DEFAULT NULL,
  modify_date DATETIME DEFAULT NULL,
  delete_id INT DEFAULT NULL,
  deleter VARCHAR(50) DEFAULT NULL,
  delete_time DATETIME DEFAULT NULL,
  UNIQUE KEY uk_lock_code (code),
  KEY idx_lock_queue_code (queue_code),
  KEY idx_lock_active (status, active_key),
  KEY idx_lock_resource (resource_table, resource_code),
  KEY idx_lock_expire (status, expire_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='yzh 队列资源锁定表';
