SET FOREIGN_KEY_CHECKS=0;
UPDATE Sys_Menu SET Icon = 'Setting' WHERE Menu_Id = 1;
UPDATE Sys_Menu SET Icon = 'HomeFilled' WHERE Menu_Id = 101;
UPDATE Sys_Menu SET Icon = 'UserFilled' WHERE Menu_Id = 102;
UPDATE Sys_Menu SET Icon = 'Menu' WHERE Menu_Id = 103;
UPDATE Sys_Menu SET Icon = 'Connection' WHERE Menu_Id = 104;
UPDATE Sys_Menu SET Icon = 'Folder' WHERE Menu_Id = 105;
UPDATE Sys_Menu SET Icon = 'Link' WHERE Menu_Id = 106;
UPDATE Sys_Menu SET Icon = 'Collection' WHERE Menu_Id = 107;
UPDATE Sys_Menu SET Icon = 'Document' WHERE Menu_Id = 108;
UPDATE Sys_Menu SET Icon = 'Tools' WHERE Menu_Id = 109;
UPDATE Sys_Menu SET Icon = 'DocumentChecked' WHERE Menu_Id = 2;
UPDATE Sys_Menu SET Icon = 'Document' WHERE Menu_Id = 201;
UPDATE Sys_Menu SET Icon = 'OfficeBuilding' WHERE Menu_Id = 202;
UPDATE Sys_Menu SET Icon = 'Date' WHERE Menu_Id = 203;
UPDATE Sys_Menu SET Icon = 'DocumentCopy' WHERE Menu_Id = 204;
UPDATE Sys_Menu SET Icon = 'Connection' WHERE Menu_Id = 205;
UPDATE Sys_Menu SET Icon = 'Operation' WHERE Menu_Id = 206;
UPDATE Sys_Menu SET Icon = 'Files' WHERE Menu_Id = 207;
UPDATE Sys_Menu SET Icon = 'Tickets' WHERE Menu_Id = 208;
UPDATE Sys_Menu SET Icon = 'Collection' WHERE Menu_Id = 209;
UPDATE Sys_Menu SET Icon = 'ChatLineRound' WHERE Menu_Id = 210;
UPDATE Sys_Menu SET Icon = 'Cpu' WHERE Menu_Id = 211;
UPDATE Sys_Menu SET Icon = 'Edit' WHERE Menu_Id = 212;
UPDATE Sys_Menu SET Icon = 'Warning' WHERE Menu_Id = 213;
UPDATE Sys_Menu SET Icon = 'SetUp' WHERE Menu_Id = 214;
UPDATE Sys_Menu SET Icon = 'Money' WHERE Menu_Id = 215;
UPDATE Sys_Menu SET Icon = 'DataAnalysis' WHERE Menu_Id = 216;
SET FOREIGN_KEY_CHECKS=1;
SELECT Menu_Id, MenuName, Icon FROM Sys_Menu ORDER BY Menu_Id;
