<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CertPlatform.Admin</RootNamespace>
    <AssemblyName>CertPlatform.Admin</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\yzh-core\YZH.Core.Api\YZH.Core.Api.csproj" />
    <ProjectReference Include="..\..\yzh-core\YZH.Core.DataBase\YZH.Core.DataBase.csproj" />
    <ProjectReference Include="..\CertPlatform.Shared\CertPlatform.Shared.csproj">
      <Aliases>SharedEntities</Aliases>
    </ProjectReference>
  </ItemGroup>

</Project>
