<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>YZH.Core.Api</RootNamespace>
    <AssemblyName>YZH.Core.Api</AssemblyName>
    <Description>YZH Core Api - Web核心层：控制器基类、EntityConfig接口、过滤器</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\server\Vue.NetCore\vol.api\YZH.Entity\YZH.Entity.csproj" />
    <ProjectReference Include="..\YZH.Core.DataBase\YZH.Core.DataBase.csproj" />
    <ProjectReference Include="..\YZH.Core.Stand\YZH.Core.Stand.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="SkiaSharp" Version="2.88.8" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux.NoDependencies" Version="2.88.8" />
  </ItemGroup>

</Project>
