-- =============================================================================
-- Skill 数据恢复（binlog 回放）
-- 来源：mysql-bin.000021（覆盖 2026-09-17 ~ 2026-09-23 15:53）
-- 起因：2026-09-24 `scripts/db/rebuild/rebuild_db.sh` 执行 DROP DATABASE，业务数据不 seed
-- 列映射：binlog 列类型序列 + 值语义双重对齐（每张表逐列校验通过）
-- 生成时间：2026-09-26 17:18:05
-- =============================================================================

SET NAMES utf8mb4 COLLATE utf8mb4_general_ci;
SET FOREIGN_KEY_CHECKS=0;

-- ===== wf_skill_category：5 行 =====
DELETE FROM `wf_skill_category`;
INSERT INTO `wf_skill_category` SET `Id` = 1, `Code` = 'f8182331-9a11-11f1-8639-6e58674aefc6', `ParentCode` = NULL, `CategoryCode` = 'data_access', `Name` = '数据获取', `Icon` = 'Folder', `Color` = '#409EFF', `SortOrder` = 1, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-08-17 16:02:19', `CreateBy` = 'system', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill_category` SET `Id` = 2, `Code` = 'f81a39dc-9a11-11f1-8639-6e58674aefc6', `ParentCode` = NULL, `CategoryCode` = 'data_process', `Name` = '数据处理', `Icon` = 'Cpu', `Color` = '#67C23A', `SortOrder` = 2, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-08-17 16:02:19', `CreateBy` = 'system', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill_category` SET `Id` = 3, `Code` = 'f81e0648-9a11-11f1-8639-6e58674aefc6', `ParentCode` = NULL, `CategoryCode` = 'ai_judge', `Name` = 'AI 判断', `Icon` = 'MagicStick', `Color` = '#E6A23C', `SortOrder` = 3, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-08-17 16:02:19', `CreateBy` = 'system', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill_category` SET `Id` = 4, `Code` = 'f82073dd-9a11-11f1-8639-6e58674aefc6', `ParentCode` = NULL, `CategoryCode` = 'ai_generate', `Name` = 'AI 生成', `Icon` = 'ChatDotRound', `Color` = '#F56C6C', `SortOrder` = 4, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-08-17 16:02:19', `CreateBy` = 'system', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill_category` SET `Id` = 5, `Code` = 'f822e7c6-9a11-11f1-8639-6e58674aefc6', `ParentCode` = NULL, `CategoryCode` = 'output', `Name` = '输出', `Icon` = 'Document', `Color` = '#909399', `SortOrder` = 5, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-08-17 16:02:19', `CreateBy` = 'system', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;

-- ===== wf_skill：5 行 =====
DELETE FROM `wf_skill`;
INSERT INTO `wf_skill` SET `Id` = 2, `Code` = 'assemble', `SkillCode` = 'assemble', `Name` = '数据组装', `SkillType` = 'manual', `CategoryCode` = 'f81a39dc-9a11-11f1-8639-6e58674aefc6', `SideEffect` = 0, `Description` = '将多个输入数据组装为结构化输出', `PromptTemplate` = NULL, `IsActive` = 1, `OutputStrict` = 1, `ReturnType` = 'json', `Version` = '1.0', `Icon` = NULL, `Color` = NULL, `SortOrder` = 1, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-09-15 11:16:56', `CreateBy` = 'USER_000001', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill` SET `Id` = 3, `Code` = 'compare', `SkillCode` = 'compare', `Name` = '值比较', `SkillType` = 'manual', `CategoryCode` = 'f81e0648-9a11-11f1-8639-6e58674aefc6', `SideEffect` = 0, `Description` = '对两个值进行比较判断', `PromptTemplate` = NULL, `IsActive` = 1, `OutputStrict` = 1, `ReturnType` = 'json', `Version` = '1.0', `Icon` = NULL, `Color` = NULL, `SortOrder` = 2, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-09-15 11:16:56', `CreateBy` = 'USER_000001', `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill` SET `Id` = 4, `Code` = 'get_field', `SkillCode` = 'get_field', `Name` = '获取字段值', `SkillType` = 'method', `CategoryCode` = 'f8182331-9a11-11f1-8639-6e58674aefc6', `SideEffect` = 0, `Description` = '按字段编码和企业编码查询已提取的文档字段值（ent_extraction_result）', `PromptTemplate` = NULL, `IsActive` = 1, `OutputStrict` = 1, `ReturnType` = 'json', `Version` = '1.0', `Icon` = NULL, `Color` = NULL, `SortOrder` = 30, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-09-17 09:46:35', `CreateBy` = NULL, `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill` SET `Id` = 5, `Code` = 'get_table', `SkillCode` = 'get_table', `Name` = '获取表格数据', `SkillType` = 'method', `CategoryCode` = 'f8182331-9a11-11f1-8639-6e58674aefc6', `SideEffect` = 0, `Description` = '按表格编码和企业编码查询已提取的表格数据（ent_table_extraction_result）', `PromptTemplate` = NULL, `IsActive` = 1, `OutputStrict` = 1, `ReturnType` = 'json', `Version` = '1.0', `Icon` = NULL, `Color` = NULL, `SortOrder` = 40, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-09-17 09:46:35', `CreateBy` = NULL, `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;
INSERT INTO `wf_skill` SET `Id` = 6, `Code` = 'llm_extract', `SkillCode` = 'llm_extract', `Name` = 'LLM提取', `SkillType` = 'method', `CategoryCode` = 'f82073dd-9a11-11f1-8639-6e58674aefc6', `SideEffect` = 0, `Description` = '渲染提示词 → 调 LLM → 解析结构化 JSON 输出（DI 注册式，无需反射登记）', `PromptTemplate` = NULL, `IsActive` = 1, `OutputStrict` = 1, `ReturnType` = 'json', `Version` = '1.0', `Icon` = NULL, `Color` = NULL, `SortOrder` = 50, `Remark` = NULL, `IsDeleted` = 0, `IsValid` = 1, `CreateTime` = '2026-09-17 09:46:35', `CreateBy` = NULL, `UpdateTime` = NULL, `UpdateBy` = NULL, `DeleteTime` = NULL, `DeleteBy` = NULL;

-- ===== wf_skill_input：6 行 =====
DELETE FROM `wf_skill_input`;
INSERT INTO `wf_skill_input` SET `Id` = 34, `Code` = 'e7377deab8ca4996a76e977ebe7d566b', `SkillCode` = 'compare', `InputName` = 'value_a', `InputLabel` = '比较值 A（数值/日期/字符串）', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'LinkOrConstant', `EnumSource` = NULL, `SortOrder` = 1, `CreateTime` = '2026-08-20 10:04:50', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_input` SET `Id` = 35, `Code` = '265c65cbf2684525b6b62383b40643af', `SkillCode` = 'compare', `InputName` = 'value_b', `InputLabel` = '比较值 B（数值/日期/字符串）', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'LinkOrConstant', `EnumSource` = NULL, `SortOrder` = 2, `CreateTime` = '2026-08-20 10:04:50', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_input` SET `Id` = 36, `Code` = '7e3dc913d05f499c88e3d3e925e6ebfe', `SkillCode` = 'compare', `InputName` = 'operator', `InputLabel` = '运算符', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'Enum', `EnumSource` = 'compare_operator', `SortOrder` = 3, `CreateTime` = '2026-08-20 10:04:50', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_input` SET `Id` = 37, `Code` = '43d2cc0440be478f94572bd60c02626c', `SkillCode` = 'assemble', `InputName` = 'prefix_text', `InputLabel` = '前半部分文本（合并前）', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'LinkOrConstant', `EnumSource` = NULL, `SortOrder` = 1, `CreateTime` = '2026-08-20 10:08:13', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_input` SET `Id` = 38, `Code` = '1f085c2c48454d25ab6a4499d1418ca8', `SkillCode` = 'assemble', `InputName` = 'suffix_text', `InputLabel` = '后半部分文本（合并后）', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'LinkOrConstant', `EnumSource` = NULL, `SortOrder` = 2, `CreateTime` = '2026-08-20 10:08:13', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_input` SET `Id` = 39, `Code` = '2520cbbb049042a0814c6966509f0ca1', `SkillCode` = 'assemble', `InputName` = 'joiner', `InputLabel` = '连接符（空=直接拼接）', `InputType` = 'string', `EnumValues` = NULL, `IsRequired` = 0, `DefaultValue` = NULL, `BindMode` = 'LinkOrConstant', `EnumSource` = NULL, `SortOrder` = 3, `CreateTime` = '2026-08-20 10:08:13', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;

-- ===== wf_skill_output：2 行 =====
DELETE FROM `wf_skill_output`;
INSERT INTO `wf_skill_output` SET `Id` = 34, `Code` = '4b7ed5b0dc824772bc9d9f7f7a146a9a', `SkillCode` = 'compare', `OutputName` = 'result', `OutputType` = 'boolean', `OutputPrompt` = NULL, `Description` = '执行结果', `SortOrder` = 1, `CreateTime` = '2026-08-20 10:04:50', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_output` SET `Id` = 35, `Code` = 'd121477ecfb047bf9cddb7516dba4733', `SkillCode` = 'assemble', `OutputName` = 'result', `OutputType` = 'string', `OutputPrompt` = NULL, `Description` = '执行结果', `SortOrder` = 1, `CreateTime` = '2026-08-20 10:08:13', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;

-- ===== wf_skill_reflection：4 行 =====
DELETE FROM `wf_skill_reflection`;
INSERT INTO `wf_skill_reflection` SET `Id` = 17, `Code` = '89ae49cf19664d7bb1bda579fa6af52a', `SkillCode` = 'compare', `ClassPath` = 'CertPlatform.Admin.Services.Workflow.Skills.CompareSkill', `MethodName` = 'ExecuteAsync', `ParamBinding` = NULL, `CreateTime` = '2026-08-20 10:04:50', `UpdateTime` = '2026-09-17 09:46:35', `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_reflection` SET `Id` = 18, `Code` = '0f0003ffe38d4035b83c13fdd8b13f66', `SkillCode` = 'assemble', `ClassPath` = 'CertPlatform.Admin.Services.Workflow.Skills.AssembleSkill', `MethodName` = 'ExecuteAsync', `ParamBinding` = NULL, `CreateTime` = '2026-08-20 10:08:13', `UpdateTime` = '2026-09-17 09:46:35', `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = 'admin', `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_reflection` SET `Id` = 19, `Code` = '9dcddc90b23911f19e5eae09e88bd2e9', `SkillCode` = 'get_field', `ClassPath` = 'CertPlatform.Admin.Services.Workflow.Skills.GetFieldSkill', `MethodName` = 'ExecuteAsync', `ParamBinding` = NULL, `CreateTime` = '2026-09-17 09:46:35', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = NULL, `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;
INSERT INTO `wf_skill_reflection` SET `Id` = 20, `Code` = '9dcde4b6b23911f19e5eae09e88bd2e9', `SkillCode` = 'get_table', `ClassPath` = 'CertPlatform.Admin.Services.Workflow.Skills.GetTableSkill', `MethodName` = 'ExecuteAsync', `ParamBinding` = NULL, `CreateTime` = '2026-09-17 09:46:35', `UpdateTime` = NULL, `DeleteTime` = NULL, `Status` = 'active', `Remark` = NULL, `CreateBy` = NULL, `UpdateBy` = NULL, `DeleteBy` = NULL, `IsDeleted` = 0, `IsValid` = 1;

SET FOREIGN_KEY_CHECKS=1;

SELECT 'wf_skill_category' AS 表, COUNT(*) AS 行数 FROM wf_skill_category
UNION ALL SELECT 'wf_skill', COUNT(*) FROM wf_skill
UNION ALL SELECT 'wf_skill_input', COUNT(*) FROM wf_skill_input
UNION ALL SELECT 'wf_skill_output', COUNT(*) FROM wf_skill_output
UNION ALL SELECT 'wf_skill_reflection', COUNT(*) FROM wf_skill_reflection;