-- Phase 7 Fix: 为 wf_skill 表补全 YZHBaseEntity 审计字段
USE yzh_cert_platform;

-- 添加 enable 字段（逻辑删除标记）
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS enable TINYINT(1) NOT NULL DEFAULT 1 COMMENT '启用状态: 1=启用, 0=禁用/逻辑删除';

-- 添加 audit 字段
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS create_id INT NULL COMMENT '创建人ID';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS creator VARCHAR(50) NULL COMMENT '创建人姓名';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS create_date DATETIME NULL COMMENT '创建时间';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS modify_id INT NULL COMMENT '修改人ID';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS modifier VARCHAR(50) NULL COMMENT '修改人姓名';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS modify_date DATETIME NULL COMMENT '修改时间';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS delete_id INT NULL COMMENT '删除人ID';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS deleter VARCHAR(50) NULL COMMENT '删除人姓名';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS delete_time DATETIME NULL COMMENT '删除时间';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS status VARCHAR(50) NULL DEFAULT 'active' COMMENT '业务状态';
ALTER TABLE wf_skill ADD COLUMN IF NOT EXISTS remark VARCHAR(500) NULL COMMENT '备注';
