<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="/Volumes/Expand/wangqingquan/Documents/work/study/体系认证平台/src/yzh-core/YZH.Core.Stand/YZH.Core.Stand.csproj" />
  </ItemGroup>
</Project>
